# Generated by `modde dev export-tool-schema`. Do not edit by hand.
{
  "gamemode" = {
  };
  "mangohud" = {
    "af" = {
      type = "int";
      default = null;
      description = "Anisotropic filtering override.";
      advanced = false;
      min = 0;
      max = 16;
      step = 1;
    };
    "arch" = {
      type = "bool";
      default = null;
      description = "Show process architecture.";
      advanced = false;
    };
    "autostart_log" = {
      type = "bool";
      default = null;
      description = "Start logging automatically.";
      advanced = false;
    };
    "background_alpha" = {
      type = "float";
      default = null;
      description = "HUD background opacity.";
      advanced = false;
      min = 0;
      max = 1;
      step = 0.05;
    };
    "background_color" = {
      type = "text";
      default = null;
      description = "HUD background color, such as 020202.";
      advanced = false;
    };
    "battery" = {
      type = "bool";
      default = null;
      description = "Show battery state.";
      advanced = false;
    };
    "battery_color" = {
      type = "text";
      default = null;
      description = "Battery text color.";
      advanced = false;
    };
    "battery_time" = {
      type = "bool";
      default = null;
      description = "Show battery time remaining.";
      advanced = false;
    };
    "battery_watt" = {
      type = "bool";
      default = null;
      description = "Show battery power draw.";
      advanced = false;
    };
    "bicubic" = {
      type = "bool";
      default = null;
      description = "Enable bicubic scaling flag.";
      advanced = false;
    };
    "core_bars" = {
      type = "bool";
      default = null;
      description = "Show per-core bars.";
      advanced = false;
    };
    "core_load" = {
      type = "bool";
      default = null;
      description = "Show per-core load.";
      advanced = false;
    };
    "core_type" = {
      type = "bool";
      default = null;
      description = "Show CPU core types.";
      advanced = false;
    };
    "cpu_color" = {
      type = "text";
      default = null;
      description = "CPU text color.";
      advanced = false;
    };
    "cpu_efficiency" = {
      type = "bool";
      default = null;
      description = "Show CPU efficiency.";
      advanced = false;
    };
    "cpu_load_change" = {
      type = "bool";
      default = null;
      description = "Show CPU load changes.";
      advanced = false;
    };
    "cpu_mhz" = {
      type = "bool";
      default = null;
      description = "Show CPU clock speed.";
      advanced = false;
    };
    "cpu_power" = {
      type = "bool";
      default = null;
      description = "Show CPU power.";
      advanced = false;
    };
    "cpu_stats" = {
      type = "bool";
      default = null;
      description = "Show CPU load and clocks.";
      advanced = false;
    };
    "cpu_temp" = {
      type = "bool";
      default = null;
      description = "Show CPU temperature.";
      advanced = false;
    };
    "cpu_text" = {
      type = "text";
      default = null;
      description = "Custom CPU label.";
      advanced = false;
    };
    "custom_text_center" = {
      type = "text";
      default = null;
      description = "Custom text shown in the HUD center column.";
      advanced = false;
    };
    "device_battery" = {
      type = "bool";
      default = null;
      description = "Show controller/device battery.";
      advanced = false;
    };
    "display_server" = {
      type = "bool";
      default = null;
      description = "Show display server.";
      advanced = false;
    };
    "engine_color" = {
      type = "text";
      default = null;
      description = "Engine text color.";
      advanced = false;
    };
    "engine_short_names" = {
      type = "bool";
      default = null;
      description = "Shorten engine names.";
      advanced = false;
    };
    "engine_version" = {
      type = "bool";
      default = null;
      description = "Show game engine version.";
      advanced = false;
    };
    "exec" = {
      type = "text";
      default = null;
      description = "Command executed by MangoHud.";
      advanced = false;
    };
    "fcat" = {
      type = "bool";
      default = null;
      description = "Show FCAT overlay.";
      advanced = false;
    };
    "fex_stats" = {
      type = "bool";
      default = null;
      description = "Show FEX stats.";
      advanced = false;
    };
    "flip_efficiency" = {
      type = "bool";
      default = null;
      description = "Show flip efficiency.";
      advanced = false;
    };
    "font_file" = {
      type = "path";
      default = null;
      description = "Optional font file path.";
      advanced = false;
    };
    "font_size" = {
      type = "int";
      default = null;
      description = "HUD font size.";
      advanced = false;
      min = 6;
      max = 48;
      step = 1;
    };
    "fps" = {
      type = "bool";
      default = null;
      description = "Show the current frame rate.";
      advanced = false;
    };
    "fps_color" = {
      type = "text";
      default = null;
      description = "FPS text color.";
      advanced = false;
    };
    "fps_color_change" = {
      type = "bool";
      default = null;
      description = "Change FPS color by threshold.";
      advanced = false;
    };
    "fps_limit" = {
      type = "text";
      default = null;
      description = "FPS limit list or value.";
      advanced = false;
    };
    "fps_limit_method" = {
      type = "enum";
      default = null;
      description = "MangoHud FPS limiter mode.";
      advanced = false;
      values = [ "late" "early" ];
    };
    "fps_metrics" = {
      type = "text";
      default = null;
      description = "Low-percentile FPS metrics, such as 0.01 or 0.001.";
      advanced = false;
    };
    "frame_count" = {
      type = "bool";
      default = null;
      description = "Show rendered frame count.";
      advanced = false;
    };
    "frame_timing" = {
      type = "bool";
      default = null;
      description = "Show frame timing data.";
      advanced = false;
    };
    "frametime" = {
      type = "bool";
      default = null;
      description = "Show frame-time graph data.";
      advanced = false;
    };
    "frametime_color" = {
      type = "text";
      default = null;
      description = "Frame-time text color.";
      advanced = false;
    };
    "fsr" = {
      type = "bool";
      default = null;
      description = "Show FSR state.";
      advanced = false;
    };
    "gamemode" = {
      type = "bool";
      default = null;
      description = "Show GameMode status.";
      advanced = false;
    };
    "gl_vsync" = {
      type = "enum";
      default = null;
      description = "OpenGL VSync setting.";
      advanced = false;
      values = [ "-1" "0" "1" "n" ];
    };
    "gpu_color" = {
      type = "text";
      default = null;
      description = "GPU text color.";
      advanced = false;
    };
    "gpu_core_clock" = {
      type = "bool";
      default = null;
      description = "Show GPU core clock.";
      advanced = false;
    };
    "gpu_efficiency" = {
      type = "bool";
      default = null;
      description = "Show GPU efficiency.";
      advanced = false;
    };
    "gpu_fan" = {
      type = "bool";
      default = null;
      description = "Show GPU fan speed.";
      advanced = false;
    };
    "gpu_junction_temp" = {
      type = "bool";
      default = null;
      description = "Show GPU junction temperature.";
      advanced = false;
    };
    "gpu_list" = {
      type = "text";
      default = null;
      description = "GPU list selector.";
      advanced = false;
    };
    "gpu_load_change" = {
      type = "bool";
      default = null;
      description = "Show GPU load changes.";
      advanced = false;
    };
    "gpu_mem_clock" = {
      type = "bool";
      default = null;
      description = "Show GPU memory clock.";
      advanced = false;
    };
    "gpu_mem_temp" = {
      type = "bool";
      default = null;
      description = "Show GPU memory temperature.";
      advanced = false;
    };
    "gpu_name" = {
      type = "bool";
      default = null;
      description = "Show GPU name.";
      advanced = false;
    };
    "gpu_power" = {
      type = "bool";
      default = null;
      description = "Show GPU power.";
      advanced = false;
    };
    "gpu_power_limit" = {
      type = "bool";
      default = null;
      description = "Show GPU power limit.";
      advanced = false;
    };
    "gpu_stats" = {
      type = "bool";
      default = null;
      description = "Show GPU load and clocks.";
      advanced = false;
    };
    "gpu_temp" = {
      type = "bool";
      default = null;
      description = "Show GPU temperature.";
      advanced = false;
    };
    "gpu_text" = {
      type = "text";
      default = null;
      description = "Custom GPU label.";
      advanced = false;
    };
    "gpu_voltage" = {
      type = "bool";
      default = null;
      description = "Show GPU voltage.";
      advanced = false;
    };
    "hdr" = {
      type = "bool";
      default = null;
      description = "Show HDR state.";
      advanced = false;
    };
    "histogram" = {
      type = "bool";
      default = null;
      description = "Show frame-time histogram.";
      advanced = false;
    };
    "horizontal" = {
      type = "bool";
      default = null;
      description = "Use horizontal HUD layout.";
      advanced = false;
    };
    "hud_compact" = {
      type = "bool";
      default = null;
      description = "Use MangoHud compact HUD layout.";
      advanced = false;
    };
    "io_color" = {
      type = "text";
      default = null;
      description = "IO text color.";
      advanced = false;
    };
    "io_read" = {
      type = "bool";
      default = null;
      description = "Show disk read throughput.";
      advanced = false;
    };
    "io_write" = {
      type = "bool";
      default = null;
      description = "Show disk write throughput.";
      advanced = false;
    };
    "log_duration" = {
      type = "int";
      default = null;
      description = "Log duration in seconds.";
      advanced = false;
      min = 0;
      max = 86400;
      step = 1;
    };
    "log_interval" = {
      type = "int";
      default = null;
      description = "Logging interval.";
      advanced = false;
      min = 0;
      max = 10000;
      step = 1;
    };
    "log_versioning" = {
      type = "bool";
      default = null;
      description = "Version MangoHud log files.";
      advanced = false;
    };
    "media_player" = {
      type = "bool";
      default = null;
      description = "Show media player information.";
      advanced = false;
    };
    "media_player_color" = {
      type = "text";
      default = null;
      description = "Media player text color.";
      advanced = false;
    };
    "network" = {
      type = "bool";
      default = null;
      description = "Show network throughput.";
      advanced = false;
    };
    "no_display" = {
      type = "bool";
      default = null;
      description = "Collect/log without showing the overlay.";
      advanced = false;
    };
    "offset_x" = {
      type = "int";
      default = null;
      description = "Horizontal overlay offset.";
      advanced = false;
      min = -400;
      max = 400;
      step = 1;
    };
    "offset_y" = {
      type = "int";
      default = null;
      description = "Vertical overlay offset.";
      advanced = false;
      min = -400;
      max = 400;
      step = 1;
    };
    "output_folder" = {
      type = "path";
      default = null;
      description = "MangoHud log output folder.";
      advanced = false;
    };
    "pci_dev" = {
      type = "text";
      default = null;
      description = "PCI device selector.";
      advanced = false;
    };
    "picmip" = {
      type = "int";
      default = null;
      description = "Texture picmip override.";
      advanced = false;
      min = -10;
      max = 10;
      step = 1;
    };
    "position" = {
      type = "enum";
      default = null;
      description = "Screen corner used for the MangoHud overlay.";
      advanced = false;
      values = [ "top-left" "top-center" "top-right" "middle-left" "middle-right" "bottom-left" "bottom-center" "bottom-right" ];
    };
    "present_mode" = {
      type = "bool";
      default = null;
      description = "Show present mode.";
      advanced = false;
    };
    "proc_vram" = {
      type = "bool";
      default = null;
      description = "Show process VRAM.";
      advanced = false;
    };
    "procmem" = {
      type = "bool";
      default = null;
      description = "Show process memory.";
      advanced = false;
    };
    "ram" = {
      type = "bool";
      default = null;
      description = "Show RAM usage.";
      advanced = false;
    };
    "ram_color" = {
      type = "text";
      default = null;
      description = "RAM text color.";
      advanced = false;
    };
    "ram_temp" = {
      type = "bool";
      default = null;
      description = "Show RAM temperature.";
      advanced = false;
    };
    "refresh_rate" = {
      type = "bool";
      default = null;
      description = "Show refresh rate.";
      advanced = false;
    };
    "resolution" = {
      type = "bool";
      default = null;
      description = "Show resolution.";
      advanced = false;
    };
    "retro" = {
      type = "bool";
      default = null;
      description = "Enable retro scaling flag.";
      advanced = false;
    };
    "round_corners" = {
      type = "int";
      default = null;
      description = "HUD background corner radius.";
      advanced = false;
      min = 0;
      max = 32;
      step = 1;
    };
    "show_fps_limit" = {
      type = "bool";
      default = null;
      description = "Show active FPS limit.";
      advanced = false;
    };
    "swap" = {
      type = "bool";
      default = null;
      description = "Show swap usage.";
      advanced = false;
    };
    "table_columns" = {
      type = "int";
      default = null;
      description = "MangoHud table column count.";
      advanced = false;
      min = 1;
      max = 8;
      step = 1;
    };
    "temp_fahrenheit" = {
      type = "bool";
      default = null;
      description = "Show temperatures in Fahrenheit.";
      advanced = false;
    };
    "text_color" = {
      type = "text";
      default = null;
      description = "Default HUD text color.";
      advanced = false;
    };
    "throttling_status" = {
      type = "bool";
      default = null;
      description = "Show throttling status.";
      advanced = false;
    };
    "throttling_status_graph" = {
      type = "bool";
      default = null;
      description = "Show throttling graph.";
      advanced = false;
    };
    "time" = {
      type = "bool";
      default = null;
      description = "Show clock.";
      advanced = false;
    };
    "toggle_fps_limit" = {
      type = "text";
      default = null;
      description = "Key used to toggle FPS limiting.";
      advanced = false;
    };
    "toggle_hud" = {
      type = "text";
      default = null;
      description = "Key used to toggle the HUD.";
      advanced = false;
    };
    "toggle_logging" = {
      type = "text";
      default = null;
      description = "Key used to toggle logging.";
      advanced = false;
    };
    "trilinear" = {
      type = "bool";
      default = null;
      description = "Enable trilinear filtering flag.";
      advanced = false;
    };
    "upload_logs" = {
      type = "bool";
      default = null;
      description = "Enable MangoHud log upload integration.";
      advanced = false;
    };
    "version" = {
      type = "bool";
      default = null;
      description = "Show MangoHud version.";
      advanced = false;
    };
    "vkbasalt" = {
      type = "bool";
      default = null;
      description = "Show vkBasalt status.";
      advanced = false;
    };
    "vram" = {
      type = "bool";
      default = null;
      description = "Show VRAM usage.";
      advanced = false;
    };
    "vram_color" = {
      type = "text";
      default = null;
      description = "VRAM text color.";
      advanced = false;
    };
    "vsync" = {
      type = "text";
      default = null;
      description = "VSync setting.";
      advanced = false;
    };
    "vulkan_driver" = {
      type = "bool";
      default = null;
      description = "Show Vulkan driver.";
      advanced = false;
    };
    "wine" = {
      type = "bool";
      default = null;
      description = "Show Wine/Proton version.";
      advanced = false;
    };
    "wine_color" = {
      type = "text";
      default = null;
      description = "Wine text color.";
      advanced = false;
    };
    "winesync" = {
      type = "bool";
      default = null;
      description = "Show Wine sync method.";
      advanced = false;
    };
  };
  "optiscaler" = {
    "copy_companion_files" = {
      type = "bool";
      default = null;
      description = "Copy fakenvapi, nvngx wrapper, and other DLLs found next to OptiScaler.";
      advanced = false;
    };
    "dll_overrides" = {
      type = "text";
      default = null;
      description = "Comma or whitespace separated Wine DLL override base names.";
      advanced = false;
    };
    "emulate_fp8" = {
      type = "bool";
      default = null;
      description = "Set DXIL_SPIRV_CONFIG=wmma_rdna3_workaround for the Latest (FP8) FSR4 variant.";
      advanced = false;
    };
    "enable_optipatcher" = {
      type = "bool";
      default = null;
      description = "Use OptiPatcher to unlock DLSS and DLSS frame generation inputs without whole-game spoofing in supported games.";
      advanced = false;
    };
    "fsr4_variant" = {
      type = "enum";
      default = null;
      description = "FSR4 payload copied as amd_fidelityfx_upscaler_dx12.dll.";
      advanced = false;
      values = [ "latest_fp8" "int8_402" ];
    };
    "ini_overrides.FSR.FGIndex" = {
      type = "enum";
      default = null;
      description = "OptiScaler [FSR] FGIndex override.";
      advanced = false;
      values = [ "auto" "0" "1" ];
    };
    "ini_overrides.FSR.UpscalerIndex" = {
      type = "enum";
      default = null;
      description = "OptiScaler [FSR] UpscalerIndex override.";
      advanced = false;
      values = [ "auto" "0" "1" "2" ];
    };
    "ini_overrides.Menu.Scale" = {
      type = "float";
      default = null;
      description = "OptiScaler [Menu] Scale override.";
      advanced = false;
      min = 0.5;
      max = 2;
      step = 0.1;
    };
    "ini_overrides.Menu.ShortcutKey" = {
      type = "enum";
      default = null;
      description = "OptiScaler [Menu] ShortcutKey override.";
      advanced = false;
      values = [ "auto" "INSERT" "HOME" "END" "DELETE" "BACKQUOTE" "F1" "F2" "F3" "F4" "F5" "F6" "F7" "F8" "F9" "F10" "F11" "F12" ];
    };
    "ini_overrides.NvApi.OverrideNvapiDll" = {
      type = "tri_state_bool";
      default = null;
      description = "OptiScaler OverrideNvapiDll override.";
      advanced = false;
    };
    "ini_overrides.fakenvapi.enable_trace_logs" = {
      type = "tri_state_bool";
      default = null;
      description = "fakenvapi enable_trace_logs override.";
      advanced = false;
    };
    "ini_overrides.fakenvapi.force_latencyflex" = {
      type = "tri_state_bool";
      default = null;
      description = "fakenvapi force_latencyflex override.";
      advanced = false;
    };
    "ini_overrides.fakenvapi.force_reflex" = {
      type = "enum";
      default = null;
      description = "fakenvapi force_reflex override.";
      advanced = false;
      values = [ "0" "1" "2" ];
    };
    "ini_overrides.fakenvapi.latencyflex_mode" = {
      type = "enum";
      default = null;
      description = "fakenvapi latencyflex_mode override.";
      advanced = false;
      values = [ "0" "1" "2" ];
    };
    "proxy_dll" = {
      type = "enum";
      default = null;
      description = "DLL name used to load OptiScaler for this game.";
      advanced = false;
      values = [ "dxgi.dll" "version.dll" "dbghelp.dll" "d3d12.dll" "wininet.dll" "winhttp.dll" "winmm.dll" "nvngx.dll" "OptiScaler.asi" ];
    };
    "source_mode" = {
      type = "enum";
      default = null;
      description = "Where modde should get OptiScaler files from.";
      advanced = false;
      values = [ "github_release" "goverlay_builds" "goverlay_fgmod" "local_dir" ];
    };
    "spoof_dlss" = {
      type = "bool";
      default = null;
      description = "Fallback DXGI spoofing path for games that still need whole-game spoofing.";
      advanced = false;
    };
  };
  "proton" = {
    "dll_override_mode" = {
      type = "enum";
      default = null;
      description = "How Proton should contribute forced DLL overrides.";
      advanced = false;
      values = [ "auto" "forced" "off" ];
    };
    "enable_hdr_wsi" = {
      type = "bool";
      default = null;
      description = "Export ENABLE_HDR_WSI=1.";
      advanced = false;
    };
    "enable_mesa_antilag" = {
      type = "bool";
      default = null;
      description = "Export ENABLE_LAYER_MESA_ANTI_LAG=1.";
      advanced = false;
    };
    "extra_env" = {
      type = "text";
      default = null;
      description = "Additional KEY=VALUE lines exported when launching the game.";
      advanced = false;
    };
    "forced_dll_overrides" = {
      type = "text";
      default = null;
      description = "Comma or whitespace separated DLL base names, such as dxgi, winmm.";
      advanced = false;
    };
    "glx_vendor_mesa" = {
      type = "bool";
      default = null;
      description = "Export __GLX_VENDOR_LIBRARY_NAME=mesa.";
      advanced = false;
    };
    "install_target" = {
      type = "enum";
      default = null;
      description = "Target application passed to protonup-rs.";
      advanced = false;
      values = [ "steam" ];
    };
    "mesa_loader_zink" = {
      type = "bool";
      default = null;
      description = "Export MESA_LOADER_DRIVER_OVERRIDE=zink.";
      advanced = false;
    };
    "prefix_path_override" = {
      type = "path";
      default = null;
      description = "Optional Proton/Wine prefix override. Leave blank to use launcher detection.";
      advanced = false;
    };
    "proton_dlss_upgrade" = {
      type = "bool";
      default = null;
      description = "Export PROTON_DLSS_UPGRADE=1.";
      advanced = false;
    };
    "proton_enable_hdr" = {
      type = "bool";
      default = null;
      description = "Export PROTON_ENABLE_HDR=1.";
      advanced = false;
    };
    "proton_enable_nvapi" = {
      type = "bool";
      default = null;
      description = "Export PROTON_ENABLE_NVAPI=1.";
      advanced = false;
    };
    "proton_enable_wayland" = {
      type = "bool";
      default = null;
      description = "Export PROTON_ENABLE_WAYLAND=1.";
      advanced = false;
    };
    "proton_force_large_address_aware" = {
      type = "bool";
      default = null;
      description = "Export PROTON_FORCE_LARGE_ADDRESS_AWARE=1.";
      advanced = false;
    };
    "proton_fsr4_upgrade" = {
      type = "bool";
      default = null;
      description = "Export PROTON_FSR4_UPGRADE=1.";
      advanced = false;
    };
    "proton_heap_delay_free" = {
      type = "bool";
      default = null;
      description = "Export PROTON_HEAP_DELAY_FREE=1.";
      advanced = false;
    };
    "proton_hide_nvidia_gpu" = {
      type = "bool";
      default = null;
      description = "Export PROTON_HIDE_NVIDIA_GPU=1.";
      advanced = false;
    };
    "proton_log" = {
      type = "bool";
      default = null;
      description = "Export PROTON_LOG=1.";
      advanced = false;
    };
    "proton_no_ntsync" = {
      type = "bool";
      default = null;
      description = "Export PROTON_NO_NTSYNC=1.";
      advanced = false;
    };
    "proton_priority_high" = {
      type = "bool";
      default = null;
      description = "Export PROTON_PRIORITY_HIGH=1.";
      advanced = false;
    };
    "proton_use_sdl" = {
      type = "bool";
      default = null;
      description = "Export PROTON_USE_SDL=1.";
      advanced = false;
    };
    "proton_use_wined3d" = {
      type = "bool";
      default = null;
      description = "Export PROTON_USE_WINED3D=1.";
      advanced = false;
    };
    "proton_use_wow64" = {
      type = "bool";
      default = null;
      description = "Export PROTON_USE_WOW64=1.";
      advanced = false;
    };
    "proton_xess_upgrade" = {
      type = "bool";
      default = null;
      description = "Export PROTON_XESS_UPGRADE=1.";
      advanced = false;
    };
    "radv_debug_nofastclears" = {
      type = "bool";
      default = null;
      description = "Export RADV_DEBUG=nofastclears.";
      advanced = false;
    };
    "radv_perftest_rt" = {
      type = "bool";
      default = null;
      description = "Export RADV_PERFTEST=rt,emulate_rt.";
      advanced = false;
    };
    "selected_version" = {
      type = "enum";
      default = null;
      description = "Installed or requested GEProton version.";
      advanced = false;
      values = [ "latest" ];
    };
    "staging_shared_memory" = {
      type = "bool";
      default = null;
      description = "Export STAGING_SHARED_MEMORY=1.";
      advanced = false;
    };
    "steamdeck" = {
      type = "bool";
      default = null;
      description = "Export SteamDeck=1.";
      advanced = false;
    };
    "version_mode" = {
      type = "enum";
      default = null;
      description = "How modde should choose the Proton runner for this game.";
      advanced = false;
      values = [ "launcher_default" "installed_version" "install_with_protonup_rs" ];
    };
    "wrapper_order" = {
      type = "enum";
      default = null;
      description = "Where Proton-specific wrapper integration should appear in the launch chain.";
      advanced = false;
      values = [ "after-modde" "before-tools" ];
    };
  };
  "reshade" = {
    "dll_name" = {
      type = "enum";
      default = null;
      description = "DLL name copied into the executable directory.";
      advanced = false;
      values = [ "dxgi.dll" "d3d11.dll" "dinput8.dll" ];
    };
    "source_dir" = {
      type = "path";
      default = null;
      description = "Directory containing ReShade DLLs, ReShade.ini, and shader folders.";
      advanced = false;
    };
  };
  "vkbasalt" = {
    "casSharpness" = {
      type = "float";
      default = null;
      description = "Contrast Adaptive Sharpening amount.";
      advanced = false;
      min = 0;
      max = 1;
      step = 0.05;
    };
    "effects" = {
      type = "text";
      default = null;
      description = "Colon or comma separated effect list, such as cas or cas:fxaa.";
      advanced = false;
    };
    "enableOnLaunch" = {
      type = "bool";
      default = null;
      description = "Start with vkBasalt effects enabled.";
      advanced = false;
    };
    "reshadeIncludePath" = {
      type = "path";
      default = null;
      description = "Optional ReShade shader include directory for vkBasalt.";
      advanced = false;
    };
    "reshadeTexturePath" = {
      type = "path";
      default = null;
      description = "Optional ReShade texture directory for vkBasalt.";
      advanced = false;
    };
    "toggleKey" = {
      type = "text";
      default = null;
      description = "Key used to toggle vkBasalt.";
      advanced = false;
    };
  };
}
