{pkgs, ...}: {
  projectRootFile = "flake.nix";

  programs.rustfmt = {
    enable = true;
    edition = "2024";
    package = pkgs.rust-bin.nightly.latest.default.override {
      extensions = ["rustfmt"];
    };
  };

  programs.alejandra = {
    enable = true;
  };

  # Generated by `modde dev export-tool-schema`; the exporter emits a different
  # list-padding style than alejandra would, and the `tool-schema-fresh` flake
  # check diffs the on-disk file against the exporter output.
  settings.formatter.alejandra.excludes = ["nix/tool-schema.nix"];

  programs.taplo.enable = true;

  programs.prettier = {
    enable = true;
    package = pkgs.prettier;
    includes = [
      "*.md"
      "*.markdown"
      "*.yaml"
      "*.yml"
    ];
  };
}
