[package]
name = "modde-cli"
version = "0.1.0"
description = "CLI interface for modde"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[package.metadata.release]
pre-release-replacements = [
    { file = "../../modde.spec", search = "^Version:\\s+.*$", replace = "Version:        {{version}}", exactly = 1 },
    { file = "../../flake.nix", search = "version = \"[0-9]+\\.[0-9]+\\.[0-9]+\";", replace = "version = \"{{version}}\";", exactly = 3 },
]

[[bin]]
name = "modde"
path = "src/main.rs"

[dependencies]
modde-core = { workspace = true }
modde-sources = { workspace = true }
modde-games = { workspace = true }
modde-ui = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
xxhash-rust = { workspace = true }
fomod-oxide = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
zip = { workspace = true }
url = "2"
notify = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
assert_cmd = "2"
