[advisories]
version = 2

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CDLA-Permissive-2.0",
  "CC0-1.0",
  "GPL-3.0",
  "ISC",
  "LicenseRef-UFL-1.0",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "NCSA",
  "OFL-1.1",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
  "bzip2-1.0.6",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://codeberg.org/caniko/rs-harbor.git",
  "https://codeberg.org/caniko/rs-memory-admission.git",
]
