use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// An entry in plugins.txt.
#[derive(Debug, Clone)]
pub struct PluginEntry {
    pub name: String,
    pub enabled: bool,
}

/// Read plugins.txt for a Bethesda game running under Steam Proton.
pub fn read_plugins_txt(app_id: u32, game_name: &str) -> Result<Vec<PluginEntry>> {
    let path = plugins_txt_path(app_id, game_name);
    read_plugins_txt_from(&path)
}

/// Read plugins.txt from an explicit path.
pub fn read_plugins_txt_from(path: &Path) -> Result<Vec<PluginEntry>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read {}", path.display()))?;

    let entries = content
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            if let Some(name) = line.strip_prefix('*') {
                PluginEntry {
                    name: name.to_string(),
                    enabled: true,
                }
            } else {
                PluginEntry {
                    name: line.to_string(),
                    enabled: false,
                }
            }
        })
        .collect();

    Ok(entries)
}

/// Write plugins.txt with the `*` prefix format.
pub fn write_plugins_txt(
    app_id: u32,
    game_name: &str,
    entries: &[PluginEntry],
) -> Result<()> {
    let path = plugins_txt_path(app_id, game_name);
    write_plugins_txt_to(&path, entries)
}

/// Write plugins.txt to an explicit path.
pub fn write_plugins_txt_to(path: &Path, entries: &[PluginEntry]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut content = String::from("# This file is generated by modde. Do not edit manually.\n");
    for entry in entries {
        if entry.enabled {
            content.push('*');
        }
        content.push_str(&entry.name);
        content.push('\n');
    }

    std::fs::write(path, &content)
        .with_context(|| format!("failed to write {}", path.display()))?;

    Ok(())
}

fn plugins_txt_path(app_id: u32, game_name: &str) -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
    PathBuf::from(home)
        .join(".local/share/Steam/steamapps/compatdata")
        .join(app_id.to_string())
        .join("pfx/drive_c/Users/steamuser/AppData/Local")
        .join(game_name)
        .join("plugins.txt")
}
