[package]
name = "modde-ui"
version = "0.2.0"
description = "GUI application for modde"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
documentation = "https://docs.rs/modde-ui"
include = [
  "../../LICENSE",
  "../../README.md",
  "CHANGELOG.md",
  "Cargo.toml",
  "src/**",
  "tests/**",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.deb]
name = "modde-ui"
maintainer = "Can H. Tartanoglu <caniko@codeberg.org>"
depends = "libc6, libgcc-s1, libssl3, libdbus-1-3, libsqlite3-0, libwayland-client0, libxkbcommon0, libvulkan1"
section = "utils"
priority = "optional"
assets = [
  [
    "../../target/release/modde-ui",
    "usr/bin/",
    "755",
  ],
  [
    "../../dist/modde-ui.desktop",
    "usr/share/applications/com.tartanoglu.modde.desktop",
    "644",
  ],
  [
    "../../dist/com.tartanoglu.modde.metainfo.xml",
    "usr/share/metainfo/com.tartanoglu.modde.metainfo.xml",
    "644",
  ],
  [
    "../../dist/com.tartanoglu.modde.png",
    "usr/share/icons/hicolor/512x512/apps/com.tartanoglu.modde.png",
    "644",
  ],
  [
    "../../LICENSE",
    "usr/share/doc/modde-ui/copyright",
    "644",
  ],
  [
    "../../README.md",
    "usr/share/doc/modde-ui/README.md",
    "644",
  ],
]

[lints]
workspace = true

[dependencies]
modde-core = { workspace = true }
modde-sources = { workspace = true }
modde-games = { workspace = true }
iced = { version = "0.14", features = ["tokio", "image", "svg", "advanced"] }
tokio = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
rfd = { workspace = true }
zip = { workspace = true }
tracing = { workspace = true }
smallvec = { workspace = true }
tracing-subscriber = { workspace = true }
fomod-oxide = { workspace = true }
image = { workspace = true }
open = { workspace = true }
unicode-segmentation = "1.12"

[dev-dependencies]
iced_test = "0.14"
tempfile = { workspace = true }
