use std::future::Future;
use std::path::PathBuf;
use std::pin::Pin;

use anyhow::Result;
use serde::{Deserialize, Serialize};

use super::ToolConfig;

/// Category of gaming tool.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolCategory {
    /// Performance HUD overlay (`MangoHud`).
    Overlay,
    /// Post-processing / shader injection (vkBasalt, `ReShade`).
    PostProcess,
    /// System performance tuning (`GameMode`).
    Performance,
    /// Upscaling / frame generation (`OptiScaler`).
    Upscaler,
}

impl std::fmt::Display for ToolCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Overlay => write!(f, "Overlay"),
            Self::PostProcess => write!(f, "Post-Processing"),
            Self::Performance => write!(f, "Performance"),
            Self::Upscaler => write!(f, "Upscaler"),
        }
    }
}

/// Whether a tool is available on the system.
#[derive(Debug, Clone)]
pub enum ToolAvailability {
    Available { version: Option<String> },
    NotInstalled { install_hint: String },
}

impl ToolAvailability {
    #[must_use]
    pub fn is_available(&self) -> bool {
        matches!(self, Self::Available { .. })
    }
}

/// A wrapper binary to chain before the game executable.
#[derive(Debug, Clone)]
pub struct WrapperEntry {
    pub exe: String,
    pub args: String,
}

/// Files applied by a tool to a game directory (for revert tracking).
#[derive(Debug, Clone, Default)]
pub struct AppliedFiles {
    /// Paths relative to the game directory.
    pub files: Vec<PathBuf>,
}

/// Non-mutating preview of what a tool apply would write.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ToolApplyPreview {
    /// Files the apply operation would manage, relative to the game directory.
    pub planned_files: Vec<PathBuf>,
    /// Planned files whose destination is missing or byte-different.
    pub changed_files: Vec<PathBuf>,
    /// Planned files whose destination already matches the expected bytes.
    pub unchanged_files: Vec<PathBuf>,
    /// Required inputs that are unavailable, such as a missing source DLL.
    pub missing_inputs: Vec<String>,
}

impl ToolApplyPreview {
    #[must_use]
    pub fn has_changes(&self) -> bool {
        !self.changed_files.is_empty()
    }

    pub fn record_file(&mut self, rel_path: PathBuf, changed: bool) {
        self.planned_files.push(rel_path.clone());
        if changed {
            self.changed_files.push(rel_path);
        } else {
            self.unchanged_files.push(rel_path);
        }
    }
}

/// A config file generated by a tool.
#[derive(Debug, Clone)]
pub struct GeneratedConfig {
    /// Absolute path where the config should be written.
    pub path: PathBuf,
    /// File content.
    pub content: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToolReleaseSummary {
    pub tag: String,
    pub name: Option<String>,
    pub published_at: Option<String>,
    pub assets: Vec<ToolReleaseAsset>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ToolReleaseAsset {
    pub name: String,
    pub download_url: String,
    pub size: u64,
}

pub type ToolReleaseListFuture<'a> =
    Pin<Box<dyn Future<Output = Result<Vec<ToolReleaseSummary>>> + Send + 'a>>;

pub type ToolReleaseInstallFuture<'a> =
    Pin<Box<dyn Future<Output = Result<ToolConfig>> + Send + 'a>>;
