[package]
name = "modde-sources"
version = "0.2.1"
description = "Download source implementations for modde"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
documentation = "https://docs.rs/modde-sources"
include = [
  "../../LICENSE",
  "../../README.md",
  "CHANGELOG.md",
  "Cargo.toml",
  "src/**",
  "tests/**",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[features]
default = []
rar = ["dep:unrar"]

[dependencies]
modde-core = { workspace = true }
modde-games = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
sha2 = { workspace = true }
xxhash-rust = { workspace = true }
tracing = { workspace = true }
keyring = { workspace = true }
keyring-core = { workspace = true }
aes = { workspace = true }
ctr = { workspace = true }
base64 = { workspace = true }
lz4_flex = { workspace = true }
zip = { workspace = true }
tempfile = { workspace = true }
smallvec = { workspace = true }
bytes = { workspace = true }
lru = { workspace = true }
parking_lot = { workspace = true }
sevenz-rust2 = { workspace = true }
zstd = { workspace = true }
httpdate = "1"
unrar = { package = "unrar-ng", version = "0.7.7", optional = true }
memory-admission = { version = "0.1.6", git = "https://codeberg.org/caniko/rs-memory-admission.git", rev = "43c603e848ccc00af222a4ad2996b37a793385e2", default-features = false, features = [
  "async",
] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
wiremock = { workspace = true }
