[package]
name = "modde-games"
version = "0.2.0"
description = "Game plugin implementations for modde"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file = "../../LICENSE"
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
documentation = "https://docs.rs/modde-games"
include = [
  "../../LICENSE",
  "../../README.md",
  "CHANGELOG.md",
  "Cargo.toml",
  "src/**",
  "tests/**",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
modde-core = { workspace = true }
fomod-oxide = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
zip = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
smallvec = { workspace = true }
dashmap = { workspace = true }
which = { workspace = true }
open = { workspace = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tracing-test = { version = "0.2", features = ["no-env-filter"] }
