steps:
  - name: check
    image: nixos/nix:latest
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix develop --command cargo fmt --all -- --check
      - nix develop --command cargo clippy --workspace -- -D warnings
      - nix develop --command just coverage-ci
      - nix develop --command cargo build --workspace --release
    when:
      - event: [push, pull_request]
